GET http://localhost:3000/equipment/
###
DELETE http://localhost:3000/equipment/64d0ce3c9e1fdcdf108ec23a
###
POST http://localhost:3000/equipment/
Content-Type: application/json

{
    "equipment_type": "temper",
    "equipment_brand": "stihl",
    "equipment_model": "42T",
    "equipment_year": 2004,
    "purchase_price": 2500.0,
    "rental_price": 75.00,
    "fuel_type": "diesel",
    "fuel_capacity": 45.0,
    "weight": 225.0,
    "maximum_reach": 0.00
}
###