GET http://localhost:3000/users/
###
POST http://localhost:3000/users/
 Content-Type: application/json

{
    "username" : "Alex", "password" : "Echo", "email" : "Alex@example.ca"

}
###
PATCH http://localhost:3000/users/Alex@example.ca
 Content-Type: application/json

{
    "username" : "Alex", "password" : "password"

}
###
DELETE http://localhost:3000/users/Alex@example.ca
###
GET http://localhost:3000/search/stinkboy